# Site settings
author: Anne Fausto
title: 
header-img: img/home-bg.png
email: a.r.fausto@gmail.com
copyright_name: Anne Fausto
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: MisZ_RaCheL
github_username:  RachelCodesToo

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
